const $=s=>document.querySelector(s); const LS='istqb-practice-v1';
let manifest, exams=new Map(), pool=[], answers={}, flags=new Set(), index=0, submitted=false, timerId, remaining=0;
const state=()=>JSON.parse(localStorage.getItem(LS)||'{"attempts":[],"wrong":[],"theme":"light"}');
const save=s=>localStorage.setItem(LS,JSON.stringify(s));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
async function init(){manifest=await fetch('data/manifest.json').then(r=>r.json()); $('#examSelect').innerHTML='<option value="all">Tất cả bộ đề</option>'+manifest.exams.map(e=>`<option value="${e.id}">${e.title} (${e.questionCount})</option>`).join(''); applyTheme(); renderStats();}
async function loadExam(id){if(!exams.has(id)){let m=manifest.exams.find(e=>e.id===id);exams.set(id,await fetch(m.file).then(r=>r.json()))}return exams.get(id)}
async function buildPool(mode='normal'){let ids=$('#examSelect').value==='all'?manifest.exams.map(e=>e.id):[$('#examSelect').value], all=[];for(const id of ids)all.push(...(await loadExam(id)).questions.map(q=>({...q,examId:id})));if(mode==='wrong'){let wrong=new Set(state().wrong);all=all.filter(q=>wrong.has(q.id));}if($('#shuffleQ').checked)all=shuffle(all);let n=$('#countSelect').value;if(n!=='all')all=all.slice(0,+n);return all}
async function start(mode='normal'){pool=await buildPool(mode);if(!pool.length){alert(mode==='wrong'?'Chưa có câu sai để luyện.':'Không có câu hỏi.');return}answers={};flags=new Set();index=0;submitted=false;remaining=Math.max(0,(+$(`#minutes`).value||0)*60);clearInterval(timerId);if(remaining){tick();timerId=setInterval(()=>{remaining--;tick();if(remaining<=0){clearInterval(timerId);submit()}},1000)}else $('#timer').textContent='Không giới hạn';$('#home').classList.add('hidden');$('#result').classList.add('hidden');$('#quiz').classList.remove('hidden');render()}
function tick(){let m=Math.floor(remaining/60),s=remaining%60;$('#timer').textContent=`${m}:${String(s).padStart(2,'0')}`}
function render(){let q=pool[index];$('#progress').textContent=`Câu ${index+1}/${pool.length}`;$('#question').innerHTML=`<h2>${q.question}</h2>${q.images.map(x=>`<img class="question-image" src="${x}" alt="Hình minh họa">`).join('')}`;let multi=q.correctAnswers.length>1, opts=$('#shuffleA').checked?(q._shuffled||(q._shuffled=shuffle(q.options))):q.options;$('#options').innerHTML=opts.map(o=>`<label class="option ${submitted?(q.correctAnswers.includes(o.id)?'correct':((answers[q.id]||[]).includes(o.id)?'wrong':'')):''}"><input ${multi?'type="checkbox"':'type="radio"'} name="answer" value="${o.id}" ${(answers[q.id]||[]).includes(o.id)?'checked':''} ${submitted?'disabled':''}><b>${o.id}.</b><span>${o.text}</span></label>`).join('')+(submitted?`<div class="explanation"><b>Đáp án: ${q.correctAnswers.join(', ')}</b><br>${q.explanation||'Chưa có lời giải.'}</div>`:'');$('#options').querySelectorAll('input').forEach(i=>i.onchange=()=>{let cur=answers[q.id]||[];if(multi){answers[q.id]=i.checked?[...new Set([...cur,i.value])]:cur.filter(x=>x!==i.value)}else answers[q.id]=[i.value];renderNav()});$('#flagBtn').textContent=flags.has(q.id)?'★ Đã đánh dấu':'☆ Đánh dấu';$('#prevBtn').disabled=index===0;$('#nextBtn').disabled=index===pool.length-1;renderNav()}
function renderNav(){$('#nav').innerHTML=pool.map((q,i)=>`<button class="nav-btn ${answers[q.id]?.length?'answered':''} ${flags.has(q.id)?'flagged':''} ${i===index?'current':''}" data-i="${i}">${i+1}</button>`).join('');$('#nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{index=+b.dataset.i;render()})}
function same(a,b){return [...a].sort().join()===[...b].sort().join()}
function submit(){if(submitted)return;submitted=true;clearInterval(timerId);let correct=pool.filter(q=>same(answers[q.id]||[],q.correctAnswers)).length, wrong=pool.filter(q=>!same(answers[q.id]||[],q.correctAnswers));let s=state();s.attempts.unshift({date:new Date().toISOString(),score:correct,total:pool.length});s.attempts=s.attempts.slice(0,20);let ws=new Set(s.wrong);pool.forEach(q=>same(answers[q.id]||[],q.correctAnswers)?ws.delete(q.id):ws.add(q.id));s.wrong=[...ws];save(s);$('#quiz').classList.add('hidden');$('#result').classList.remove('hidden');$('#score').innerHTML=`<div class="score-big">${correct}/${pool.length}</div><h2>${Math.round(correct/pool.length*100)}%</h2><p>Đúng ${correct} câu · Sai/chưa trả lời ${wrong.length} câu</p>`;renderStats()}
function renderStats(){let s=state(),last=s.attempts[0];$('#stats').innerHTML=`<b>Tiến độ:</b> ${last?`Lần gần nhất ${last.score}/${last.total} (${Math.round(last.score/last.total*100)}%)`:'Chưa có lượt làm'} · ${s.wrong.length} câu đang cần ôn lại.`}
function applyTheme(){document.body.classList.toggle('dark',state().theme==='dark')}
$('#startBtn').onclick=()=>start();$('#wrongBtn').onclick=()=>start('wrong');$('#prevBtn').onclick=()=>{if(index>0){index--;render()}};$('#nextBtn').onclick=()=>{if(index<pool.length-1){index++;render()}};$('#flagBtn').onclick=()=>{let id=pool[index].id;flags.has(id)?flags.delete(id):flags.add(id);render()};$('#submitBtn').onclick=()=>{if(confirm('Nộp bài và chấm điểm?'))submit()};$('#reviewBtn').onclick=()=>{index=0;$('#result').classList.add('hidden');$('#quiz').classList.remove('hidden');render()};$('#retryWrongBtn').onclick=async()=>{let wrong=pool.filter(q=>!same(answers[q.id]||[],q.correctAnswers));pool=wrong;answers={};flags=new Set();index=0;submitted=false;$('#result').classList.add('hidden');$('#quiz').classList.remove('hidden');render()};$('#homeBtn').onclick=()=>{location.reload()};$('#themeBtn').onclick=()=>{let s=state();s.theme=s.theme==='dark'?'light':'dark';save(s);applyTheme()};init();
